=begin
#Role Based Access Control

#The API for Role Based Access Control.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'uri'

module RBACApiClient
  class AccessApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get the permitted access for a principal in the tenant
    # @param username Unique username of the principal to obtain access for
    # @param application The application name to obtain access for the principal
    # @param [Hash] opts the optional parameters
    # @return [AccessPagination]
    def get_principal_access(username, application, opts = {})
      data, _status_code, _headers = get_principal_access_with_http_info(username, application, opts)
      data
    end

    # Get the permitted access for a principal in the tenant
    # @param username Unique username of the principal to obtain access for
    # @param application The application name to obtain access for the principal
    # @param [Hash] opts the optional parameters
    # @return [Array<(AccessPagination, Fixnum, Hash)>] AccessPagination data, response status code and response headers
    def get_principal_access_with_http_info(username, application, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccessApi.get_principal_access ...'
      end
      # verify the required parameter 'username' is set
      if @api_client.config.client_side_validation && username.nil?
        fail ArgumentError, "Missing the required parameter 'username' when calling AccessApi.get_principal_access"
      end
      # verify the required parameter 'application' is set
      if @api_client.config.client_side_validation && application.nil?
        fail ArgumentError, "Missing the required parameter 'application' when calling AccessApi.get_principal_access"
      end
      # resource path
      local_var_path = '/access/'

      # query parameters
      query_params = {}
      query_params[:'username'] = username
      query_params[:'application'] = application

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['basic_auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'AccessPagination')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccessApi#get_principal_access\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

  end
end
