=begin
#Role Based Access Control

#The API for Role Based Access Control.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'uri'

module RBACApiClient
  class AccessApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get the permitted access for a principal in the tenant
    # @param application The application name to obtain access for the principal
    # @param [Hash] opts the optional parameters
    # @option opts [String] :username Unique username of the principal to obtain access for
    # @option opts [Integer] :page_size Parameter for selecting the amount of data in a page. (default to 10)
    # @option opts [Integer] :page Parameter for selecting the page of data. (default to 1)
    # @return [AccessPagination]
    def get_principal_access(application, opts = {})
      data, _status_code, _headers = get_principal_access_with_http_info(application, opts)
      data
    end

    # Get the permitted access for a principal in the tenant
    # @param application The application name to obtain access for the principal
    # @param [Hash] opts the optional parameters
    # @option opts [String] :username Unique username of the principal to obtain access for
    # @option opts [Integer] :page_size Parameter for selecting the amount of data in a page.
    # @option opts [Integer] :page Parameter for selecting the page of data.
    # @return [Array<(AccessPagination, Fixnum, Hash)>] AccessPagination data, response status code and response headers
    def get_principal_access_with_http_info(application, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccessApi.get_principal_access ...'
      end
      # verify the required parameter 'application' is set
      if @api_client.config.client_side_validation && application.nil?
        fail ArgumentError, "Missing the required parameter 'application' when calling AccessApi.get_principal_access"
      end
      if @api_client.config.client_side_validation && !opts[:'page_size'].nil? && opts[:'page_size'] > 1000
        fail ArgumentError, 'invalid value for "opts[:"page_size"]" when calling AccessApi.get_principal_access, must be smaller than or equal to 1000.'
      end

      if @api_client.config.client_side_validation && !opts[:'page_size'].nil? && opts[:'page_size'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page_size"]" when calling AccessApi.get_principal_access, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'page'].nil? && opts[:'page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page"]" when calling AccessApi.get_principal_access, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/access/'

      # query parameters
      query_params = {}
      query_params[:'application'] = application
      query_params[:'username'] = opts[:'username'] if !opts[:'username'].nil?
      query_params[:'page_size'] = opts[:'page_size'] if !opts[:'page_size'].nil?
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['basic_auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'AccessPagination')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccessApi#get_principal_access\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

  end
end
